using Game.Audio;
using UnityEngine;

public class PlayerController : MonoBehaviour {
    public float moveSpeed = 5f;
    private Rigidbody2D rb;
    private Animator animator;
    private Vector2 movement;

    public bool canMove = true; // ğŸ”¹ ç•¶ç‚º false æ™‚ç„¡æ³•ç§»å‹•

    public bool isMoving = false; 
    public bool isFinding = false; 
    public bool isSitDown = false; 

    [Header("éŸ³æ•ˆ")]
    [SerializeField] AudioData moveAudioData;
    
    void Awake() 
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
    }

    private Vector2 lastMoveDir = Vector2.down; // é è¨­è§’è‰²åˆå§‹é¢å‘

    void Update() 
    {
        if (!canMove)
        {
            movement = Vector2.zero;
            animator.SetBool("isMoving", false);
            return;
        }

        movement.x = Input.GetAxisRaw("Horizontal");
        movement.y = Input.GetAxisRaw("Vertical");
        movement.Normalize();

        // ğŸ”¹ å„²å­˜æœ€å¾Œä¸€æ¬¡æœ‰æ•ˆçš„ç§»å‹•æ–¹å‘
        if (movement.sqrMagnitude > 0.01f)
        {
            lastMoveDir = movement;
            isMoving = true;
        }
        else
        {
            isMoving = false;
        }

        // ğŸ”¹ ä½¿ç”¨ lastMoveDir è¨­å®šå‹•ç•«æ–¹å‘
        animator.SetFloat("MoveX", lastMoveDir.x);
        animator.SetFloat("MoveY", lastMoveDir.y);

        animator.SetBool("isMoving", isMoving);
        animator.SetBool("isFinding", isFinding);
        animator.SetBool("isSitDown", isSitDown);
    }


    void FixedUpdate() 
    {
        if (!canMove)
        {
            rb.linearVelocity = Vector2.zero;
            return;
        }

        rb.linearVelocity = movement * (GameManager.Instance.MainGameMediator.RealTimePlayerData.PlayerMovementMultiplier * moveSpeed);
    }
}
